import { describe, expect, it } from "vitest";

import { parseEnv, upsertEnv } from "./env-file.js";

describe("parseEnv", () => {
  it("reads quoted and bare values, ignores comments, later keys win", () => {
    const values = parseEnv('# c\nA="1"\nB=two\nexport C=\'3\'\nA=override\n\n');
    expect([...values]).toEqual([
      ["A", "override"],
      ["B", "two"],
      ["C", "3"],
    ]);
  });
});

describe("upsertEnv", () => {
  const original = '# facilitator\nFACILITATOR_API_KEY="abc"\n\nADAPTER="mock"\n';

  it("replaces existing keys in place and appends new ones under a header", () => {
    const next = upsertEnv(
      original,
      [
        { key: "ADAPTER", value: "jumpseller" },
        { key: "AGENT_ACCOUNT", value: "GABC", comment: "the buyer" },
      ],
      "generated by bootstrap",
    );
    expect(next).toBe(
      '# facilitator\nFACILITATOR_API_KEY="abc"\n\nADAPTER="jumpseller"\n\n' +
        "# ---- generated by bootstrap ------------------------------------------------\n" +
        '# the buyer\nAGENT_ACCOUNT="GABC"\n',
    );
    expect(parseEnv(next).get("FACILITATOR_API_KEY")).toBe("abc");
  });

  it("is idempotent", () => {
    const updates = [{ key: "X", value: "1" }, { key: "ADAPTER", value: "mock" }];
    const once = upsertEnv(original, updates, "h");
    expect(upsertEnv(once, updates, "h")).toBe(once);
  });

  it("starts from nothing and quotes awkward values safely", () => {
    const next = upsertEnv("", [{ key: "K", value: 'a "b" #c' }]);
    expect(next).toBe('K="a \\"b\\" #c"\n');
    expect(parseEnv(next).get("K")).toBe('a "b" #c');
  });
});
