#!/usr/bin/env node
/**
 * `pnpm bootstrap` — creates and funds the three testnet accounts a demo
 * needs (merchant payTo, merchant signing key, agent), opens the USDC
 * trustlines, and records everything in .env.local (mode 600).
 *
 * Idempotent: keys already in .env.local are reused, funded accounts are left
 * alone, existing trustlines are not re-opened. Secrets are never printed.
 * USDC itself cannot be minted here — Circle's faucet is a web form — so the
 * script ends by telling you which address to paste there.
 */
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { readEnvFile, upsertEnv, writeEnvFile, type EnvUpdate } from "./lib/env-file.js";
import { TESTNET, fundWithFriendbot, getAccountState, openUsdcTrustline, sleep } from "./lib/network.js";
import { ROLES, resolveKeypair } from "./lib/roles.js";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const ENV_PATH = resolve(REPO_ROOT, ".env.local");

const out = (line = ""): void => {
  process.stdout.write(`${line}\n`);
};

async function ensureFunded(address: string): Promise<string> {
  const before = await getAccountState(TESTNET.horizonUrl, address);
  if (before.funded) return `already funded · ${before.nativeBalance ?? "?"} XLM`;
  await fundWithFriendbot(TESTNET.friendbotUrl, address);
  for (let attempt = 0; attempt < 10; attempt += 1) {
    const after = await getAccountState(TESTNET.horizonUrl, address);
    if (after.funded) return `funded via friendbot · ${after.nativeBalance ?? "?"} XLM`;
    await sleep(1_000);
  }
  throw new Error(`friendbot accepted ${address} but Horizon never showed the account`);
}

async function main(): Promise<void> {
  const { content, values } = await readEnvFile(ENV_PATH);
  out();
  out("Vitrinee bootstrap · Stellar testnet");
  out(`  horizon   ${TESTNET.horizonUrl}`);
  out(`  usdc      ${TESTNET.usdc.code}:${TESTNET.usdc.issuer}`);
  out();

  const resolved = ROLES.map((role) => resolveKeypair(role, values));
  const updates: EnvUpdate[] = [];
  const summary: Array<{ label: string; address: string; usdc: string | undefined }> = [];

  for (const { role, keypair, origin } of resolved) {
    const address = keypair.publicKey();
    out(`  ${role.label}`);
    out(`    account    ${address}  (${origin})`);
    out(`    xlm        ${await ensureFunded(address)}`);

    let state = await getAccountState(TESTNET.horizonUrl, address);
    if (role.usdcTrustline) {
      if (state.usdcTrustline) {
        out(`    trustline  already open · ${state.usdcBalance ?? "0"} USDC`);
      } else {
        const hash = await openUsdcTrustline(TESTNET.horizonUrl, keypair);
        out(`    trustline  opened · tx ${hash}`);
        state = await getAccountState(TESTNET.horizonUrl, address);
      }
    }
    out();

    updates.push({ key: role.publicVar, value: address, comment: role.publicComment });
    if (origin === "generated") {
      updates.push({ key: role.secretVar, value: keypair.secret(), comment: role.secretComment });
    }
    summary.push({ label: role.label, address, usdc: role.usdcTrustline ? (state.usdcBalance ?? "0") : undefined });
  }

  await writeEnvFile(ENV_PATH, upsertEnv(content, updates, "generated by pnpm bootstrap"));
  const generated = resolved.filter((r) => r.origin === "generated").length;
  out(`  wrote .env.local (mode 600) · ${generated} new secret${generated === 1 ? "" : "s"}, none printed`);
  out();

  const agent = summary.find((s) => s.label === "agent (buyer)");
  if (agent !== undefined && (agent.usdc === undefined || Number(agent.usdc) === 0)) {
    out("  Next: fund the agent with testnet USDC (Circle's faucet is a web form):");
    out(`    address  ${agent.address}`);
    out("    faucet   https://faucet.circle.com  → Stellar testnet → USDC");
    out();
  }
}

try {
  await main();
} catch (error) {
  process.stderr.write(`\nbootstrap failed: ${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
}
